import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import QueryProvider from "@/app/queryProvider";
import VerifyAuth from "@/app/auth";
import React from "react";
import Header from "@/components/Header/Header";


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">

        <body className={inter.className}>

        <QueryProvider>
            <Header/>
            <VerifyAuth/>
            <main className="flex min-h-screen flex-col items-center justify-between p-24">
                {children}
            </main>
        </QueryProvider>
        </body>

        </html>
    )
}
