apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reebelo-inventory
  namespace: argocd
spec:
  destination:
    namespace: reebelo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: reebelo-api/
    repoURL: git@github.com:weeb-vip/weeb-argocd.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values/inventory.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
