name: ci

on:
  push:
    branches: [main, backend_build]


defaults:
  run:
    working-directory: ./backend

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: set tag
        run: |
          export TAG=$(node -p "require('./auth/package.json').version" | tr -d \'\n\')
          echo "tag=$TAG" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend/auth
          build-args: |
            SERVICE_VERSION=${{ env.tag }}
          push: true
          tags: ${{ secrets.REGISTRY }}/reebelo/reebelo-auth:${{ env.tag }}